### ISSUE TITLE
call to p-some is broken

### ISSUE THREAD

**Issue by yuvallb** [sindresorhus/p-any#2]
due to the changed made a few days ago to p-some,
p-any calls p-some with parameter "1" instead of "{count:1} "

**Comment by kevva** [comment]
See https://github.com/sindresorhus/p-any/pull/1.

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/p-some/commit/5d124776f010327d068b3d9b3c23167b2eec8a9e#commitcomment-22501357

**Comment by yuvallb** [comment]
Thanks!
