### ISSUE TITLE
Cancel pending promises on resolution

### ISSUE THREAD

**Issue by silverwind** [sindresorhus/p-any#3]
For example, if one passes three promises and the first resolves, `.cancel()` the other two if they have such a method on the returned Promise. There should be an option to control this behaviour.

I think the implementation of this could be challenging based on the fact that there's no easy way to synchronously check if a Promise has resolved (https://stackoverflow.com/q/30564053).

Refs:

- https://github.com/sindresorhus/is-online/pull/43#issuecomment-348755137
- https://github.com/sindresorhus/p-timeout/commit/032432734238d696bb88aeb4a6fc5d4ffc454b17

**Comment by sindresorhus** [comment]
> There should be an option to control this behaviour.

Why? I would say we just add it by default, document it, and wait until/if it causes any problems.

> I think the implementation of this could be challenging based on the fact that there's no easy way to synchronously check if a Promise has resolved

Why do you need to synchronously check if a Promise has resolved?

**Comment by silverwind** [comment]
> Why do you need to synchronously check if a Promise has resolved?

How else would you know which `.cancel` methods to call out of the passed promises when the first completes, without calling the one that has completed?

**Comment by sindresorhus** [comment]
[Here](https://github.com/sindresorhus/p-some/blob/ce864dd82b2eacf25b8135d758f24706ace4dbff/index.js#L35), we would just cancel the other promises. To know which one is the current promise, we would just pass it in [here](https://github.com/sindresorhus/p-some/blob/ce864dd82b2eacf25b8135d758f24706ace4dbff/index.js#L57) to the `fulfilled` function, together with the resolved value. We would also have to catch them and silence the `CancelError`. But shouldn't be hard.

**Comment by silverwind** [comment]
Right, as you already keep track of what completed, this should be easy to implement. Sorry for not looking at the code earlier and making wrong asumptions.
